apiVersion: v1
kind: Secret
metadata:
  namespace: project
  name: postgres-pw-url
data:
  POSTGRES_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3MHJkQHBvc3RncmVzLXByb2plY3Qtc3ZjOjU0MzIvcG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3cwcmQ=