apiVersion: v1
kind: Secret
metadata:
  namespace: project
  name: postgres-pw-url
data:
  POSTGRES_URL: postgresql://postgres:passw0rd@postgres-project-svc:5432/postgres
  POSTGRES_PASSWORD: passw0rd